const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});


test('issue245 surgical', async ({ page }) => {
    await page.goto('/');

    const results = await page.evaluate(() => {
        const classes = [
            'btn-info',
            'nav-label',
            'analytics-stat-label',
            'btn-delete-goal',
            'btn-edit-goal',
            'form-control',
            'modal-footer'
        ];

        const container = document.createElement('div');
        container.style.cssText = 'position:absolute;top:0;left:0;visibility:hidden;';
        document.body.appendChild(container);

        const checks = {};

        for (const cls of classes) {
            const el = document.createElement('div');
            el.className = cls;
            container.appendChild(el);
            const cs = window.getComputedStyle(el);
            checks[cls] = {
                display: cs.display,
                backgroundColor: cs.backgroundColor,
                borderTopWidth: cs.borderTopWidth,
                borderTopStyle: cs.borderTopStyle,
                color: cs.color,
                textTransform: cs.textTransform,
                paddingTop: cs.paddingTop,
                fontSize: cs.fontSize,
                fontWeight: cs.fontWeight,
                letterSpacing: cs.letterSpacing,
                gap: cs.gap,
                justifyContent: cs.justifyContent,
            };
            el.remove();
        }

        container.remove();
        return checks;
    });

    // btn-info: background-color should be rgb(59, 130, 246) — differs from default transparent
    expect(results['btn-info'].backgroundColor).toBe('rgb(59, 130, 246)');

    // nav-label: text-transform should be uppercase — differs from default none
    expect(results['nav-label'].textTransform).toBe('uppercase');

    // analytics-stat-label: text-transform should be uppercase — differs from default none
    expect(results['analytics-stat-label'].textTransform).toBe('uppercase');

    // btn-delete-goal: border-top-style should be solid — differs from default none
    expect(results['btn-delete-goal'].borderTopStyle).toBe('solid');

    // btn-edit-goal: border-top-style should be solid — differs from default none
    expect(results['btn-edit-goal'].borderTopStyle).toBe('solid');

    // form-control: border-top-style should be solid — differs from default none
    expect(results['form-control'].borderTopStyle).toBe('solid');

    // modal-footer: display should be flex — differs from default block
    expect(results['modal-footer'].display).toBe('flex');
});
