// Issue #306 — product family design tokens, fixed-height shell, hash routing.
//
// In-browser proof (real Chromium; the API is fully mocked with page.route —
// no backend). The page boots the production way: the token rides the URL
// hash as #access_token=..., and /api/auth/config + /api/auth/me are mocked
// for that user.
//
//   AC-1  tokens.css loads and holds the family token set from
//         docs/design/design-system.md (IBM Plex Sans/Mono from Google
//         Fonts); --color-sidebar resolves to #16212C; the sidebar is
//         --sidebar-width (232 px) wide and painted with --color-sidebar;
//         the nav labels are plain text in order, without emoji, with the
//         .nav-icon elements retained but glyph-free; #auth-status sits at
//         the sidebar foot; the header shows the page title and the content
//         region below it alone scrolls; at 1440x900 the document itself
//         does not scroll (Dashboard, and Contacts with 200 mocked rows);
//         each page has a hash route #/<data-page> — a nav click updates
//         the hash, a reload on #/companies opens Companies, Back returns
//         to the previous page, an unknown or empty hash opens Dashboard;
//         at 900 px and below the sidebar becomes a top bar and 390x844 has
//         no horizontal page scroll.
//   AC-3  the shell chrome uses the distinct --color-* family tokens; the
//         unported page styles do not inherit them.
//   AC-4  setting location.hash from App.navigate never triggers a second
//         navigate/render/API call; the hashchange handler ignores
//         same-page and programmatic-originated updates.
//   AC-6  .nav-item.active, aria-current="page" and #page-title update
//         synchronously before any async page content write.
//
// Identity: the "(viewer)" test repeats the production boot for a NON-ADMIN
// (role 'user') and asserts the admin-only control is absent while the page
// still renders, including across a full reload.

const { test, expect } = require('@playwright/test');

// CodeAgent terminal-state hook (frontend_recipe.build_terminal_state_hook)
// CodeAgent#751: once this proof's own assertions pass, nothing on the page may still
// show a loading placeholder. A render path that never reaches its terminal state
// (data, an empty note, an error) is a defect the proof did not ask about. Elements
// under [data-loading-ok] are exempt. Generated by the engine at write time -- edit
// the generator, not this block.
test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.status !== testInfo.expectedStatus || page.isClosed()) return;
  const stuck = await page.evaluate((markers) => Array.from(document.querySelectorAll('body *')).filter((el) => {
    if (el.children.length || el.closest('[data-loading-ok]')) return false;
    const t = (el.textContent || '').trim();
    if (!t || !markers.some((m) => t === m || t.startsWith(m))) return false;
    const r = el.getBoundingClientRect();
    return r.width > 0 && r.height > 0;
  }).map((el) => {
    const p = el.closest('[data-panel]');
    const cls = (el.getAttribute('class') || '').trim().split(/\s+/)[0];
    return (p && p.getAttribute('data-panel')) || (el.tagName.toLowerCase() + (cls ? '.' + cls : ''));
  }), ["Loading data\u2026", "Loading data...", "Loading\u2026", "Loading..."]).catch(() => []);
  test.expect(stuck, `element(s) still showing a loading placeholder after the proof: ${stuck.join(', ')} -- every render path must reach a terminal state (data, an empty note or an error), or declare data-loading-ok`).toEqual([]);
});

const fs = require('fs');
const path = require('path');

const INDEX = 'file://' + path.resolve(__dirname, '..', 'index.html');
const ADMIN_TOKEN = 'dev-secret-token:admin';
const VIEWER_TOKEN = 'dev-secret-token:user';

// Emoji ranges: pictographs/symbols, arrows, misc technical, VS-16.
const EMOJI_SRC = '[\\u{1F000}-\\u{1FAFF}\\u{2190}-\\u{2BFF}\\u{2300}-\\u{23FF}\\uFE0F]';
const EMOJI_RE = new RegExp(EMOJI_SRC, 'u');

const NAV_PAGES = ['dashboard', 'contacts', 'leads', 'analytics', 'activities',
                   'templates', 'winloss', 'salesgoals', 'companies', 'settings'];
const NAV_LABELS = ['Dashboard', 'Contacts', 'Leads', 'Analytics', 'Activities',
                    'Templates', 'Win/Loss', 'Sales Goals', 'Companies', 'Settings'];

// The family token set, exactly as docs/design/design-system.md, section
// "Tokens", lists it (colours, radii, spacing) plus the shell geometry the
// design system names (--sidebar-width / --detail-width).
const TOKEN_EXPECT = {
  '--color-ground': '#eef1f4',
  '--color-surface': '#ffffff',
  '--color-sidebar': '#16212c',
  '--color-ink': '#17212b',
  '--color-ink-secondary': '#4a5865',
  '--color-border': '#dde3e9',
  '--color-border-soft': '#e6eaee',
  '--color-accent': '#1d4ed8',
  '--color-risk': '#8a3b05',
  '--color-risk-bg': '#fde8d3',
  '--radius-control': '8px',
  '--radius-card': '12px',
  '--radius-pill': '999px',
  '--space-1': '4px',
  '--space-2': '8px',
  '--space-3': '12px',
  '--space-4': '16px',
  '--space-5': '20px',
  '--space-6': '24px',
  '--space-7': '28px',
  '--sidebar-width': '232px',
};

function makeContacts(n) {
  const out = [];
  for (let i = 1; i <= n; i++) {
    const day = (i % 9) + 1;
    out.push({
      id: 'c-' + String(i).padStart(3, '0'),
      name: 'Contact ' + String(i).padStart(3, '0'),
      email: i % 5 === 0 ? null : 'contact' + i + '@example.com',
      phone: null,
      company: i % 2 === 0 ? 'Acme Corp' : null,
      status: 'active',
      notes: null,
      tags: [],
      created_at: '2026-01-0' + day + 'T08:00:00Z',
      updated_at: '2026-01-0' + day + 'T08:00:00Z',
    });
  }
  return out;
}

/**
 * Boot the page the production way: the token is in the URL hash as
 * #access_token=..., and /api/auth/config + /api/auth/me are mocked for
 * that user. Every other API call is mocked too — no backend. Google Fonts
 * is stubbed so the run never depends on the network.
 *
 * Returns the recorded API calls (method, url, authorization header).
 */
async function boot(page, token, contacts) {
  const user = token === VIEWER_TOKEN
    ? { username: 'plain-user', sub: 'u1', roles: ['user'], display_name: 'Viewer One' }
    : { username: 'admin-user', sub: 'u1', roles: ['admin'], display_name: 'Admin' };
  const calls = [];
  await page.addInitScript((cfg) => { window.AICRM_CONFIG = cfg; },
    { API_BASE_URL: 'http://localhost:9000/api' });
  await page.route('**/fonts.googleapis.com/**', (route) =>
    route.fulfill({ status: 200, contentType: 'text/css', body: '' }));
  await page.route('**/fonts.gstatic.com/**', (route) =>
    route.fulfill({ status: 200, contentType: 'font/woff2', body: '' }));
  await page.route('**/api/**', (route) => {
    const req = route.request();
    const url = req.url();
    calls.push({ method: req.method(), url, auth: req.headers()['authorization'] || '' });
    const json = (o) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(o) });
    if (/\/auth\/me/.test(url)) {
      // Mocked for THIS user. The production boot sends the hash token as a
      // Bearer header; after the hash is cleaned, reloads may arrive without
      // one (file:// session storage is not relied upon) and still resolve
      // to the same user. A foreign token does not.
      const auth = req.headers()['authorization'] || '';
      if (auth && !auth.includes(token)) return json({ authenticated: false, user: null });
      return json({ authenticated: true, user });
    }
    if (/\/auth\/config/.test(url)) return json({ auth_enabled: true });
    if (/\/health/.test(url)) return json({ status: 'ok', app_version: '0.2.3' });
    if (/\/contacts(\b|\?|$)/.test(url)) {
      // Honour the limit/offset paging used by ApiClient.getAllPages.
      const u = new URL(url);
      const limit = Math.max(1, parseInt(u.searchParams.get('limit') || String(contacts.length), 10) || contacts.length);
      const offset = Math.max(0, parseInt(u.searchParams.get('offset') || '0', 10) || 0);
      return json(contacts.slice(offset, offset + limit));
    }
    if (/\/settings/.test(url)) return json({ payload: {} });
    return json([]);
  });
  await page.goto(INDEX + '#access_token=' + encodeURIComponent(token));
  await page.waitForFunction(
    () => typeof App !== 'undefined' && !!document.getElementById('page-title'),
    { timeout: 20000 });
  await page.waitForFunction(
    () => typeof Auth !== 'undefined' && Auth.isAuthenticated && Auth.isAuthenticated(),
    { timeout: 20000 });
  return calls;
}

/** Poll a Node-side counter until it stops changing (in-flight fetches settle). */
async function stable(count, settles = 3, intervalMs = 100) {
  let prev = count();
  let n = 0;
  while (n < settles) {
    const cur = count();
    if (cur === prev) n += 1;
    else { prev = cur; n = 0; }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  return prev;
}

test('issue306 freeform', async ({ page }) => {
  test.setTimeout(120000);
  const pageErrors = [];
  page.on('pageerror', (e) => pageErrors.push(String(e)));
  page.on('dialog', (d) => d.accept());

  const calls = await boot(page, ADMIN_TOKEN, makeContacts(200));
  await page.setViewportSize({ width: 1440, height: 900 });

  // ── AC-1: production boot — the hash token was sent as a Bearer header ──
  await expect.poll(
    () => calls.some((c) => /\/auth\/me/.test(c.url) && c.auth === 'Bearer ' + ADMIN_TOKEN),
    { timeout: 10000 }).toBe(true);

  // ── AC-1: tokens.css loads and holds the family token set ──
  await page.waitForFunction(
    () => Array.from(document.styleSheets).some((ss) => (ss.href || '').includes('tokens.css')),
    { timeout: 10000 });
  const tokens = await page.evaluate((names) => {
    const cs = getComputedStyle(document.documentElement);
    const out = {};
    names.forEach((n) => { out[n] = cs.getPropertyValue(n).trim().toLowerCase(); });
    return out;
  }, Object.keys(TOKEN_EXPECT));
  for (const [name, want] of Object.entries(TOKEN_EXPECT)) {
    expect(tokens[name], `token ${name}`).toBe(want);
  }
  // IBM Plex Sans + Mono, from Google Fonts, as the family's type tokens.
  const fonts = await page.evaluate(() => {
    const cs = getComputedStyle(document.documentElement);
    return {
      sans: cs.getPropertyValue('--font-sans').trim().toLowerCase(),
      mono: cs.getPropertyValue('--font-mono').trim().toLowerCase(),
    };
  });
  expect(fonts.sans).toContain('ibm plex sans');
  expect(fonts.mono).toContain('ibm plex mono');
  const tokensCss = fs.readFileSync(path.resolve(__dirname, '..', 'css', 'tokens.css'), 'utf8');
  expect(tokensCss, 'IBM Plex Sans from Google Fonts')
    .toMatch(/@import\s+url\(\s*['"]https:\/\/fonts\.googleapis\.com\/css2\?[^'"]*IBM\+Plex\+Sans[^'"]*['"]\s*\)/);
  expect(tokensCss, 'IBM Plex Mono from Google Fonts').toMatch(/IBM\+Plex\+Mono/);

  // ── AC-1: the sidebar is --sidebar-width wide and uses --color-sidebar ──
  const sidebar = await page.evaluate(() => {
    const el = document.getElementById('sidebar');
    return {
      width: getComputedStyle(el).width,
      bg: getComputedStyle(el).backgroundColor,
    };
  });
  expect(sidebar.width, 'sidebar width is --sidebar-width (232 px)').toBe('232px');
  expect(sidebar.bg, 'sidebar background is --color-sidebar').toBe('rgb(22, 33, 44)');

  // ── AC-1: nav labels in order, plain text, no emoji in .nav-item text;
  //    the .nav-icon elements are retained with their glyphs removed ──
  const nav = await page.evaluate(() =>
    Array.from(document.querySelectorAll('.nav-item')).map((el) => {
      const icon = el.querySelector('.nav-icon');
      return {
        page: el.dataset.page,
        label: (el.querySelector('.nav-label') || el).textContent.trim(),
        text: el.textContent,
        iconPresent: !!icon,
        iconText: icon ? icon.textContent : null,
      };
    }));
  expect(nav.map((n) => n.page)).toEqual(NAV_PAGES);
  expect(nav.map((n) => n.label)).toEqual(NAV_LABELS);
  for (const item of nav) {
    expect(EMOJI_RE.test(item.text),
      `no emoji in .nav-item text: ${JSON.stringify(item.text)}`).toBe(false);
    expect(item.iconPresent, '.nav-icon element retained').toBe(true);
    expect((item.iconText || '').trim(), '.nav-icon glyph removed from DOM text').toBe('');
  }

  // ── AC-1: the signed-in user (#auth-status) sits at the sidebar foot ──
  const authPos = await page.evaluate(() => ({
    inFooter: !!document.querySelector('#sidebar .sidebar-footer')
      && document.querySelector('#sidebar .sidebar-footer')
        .contains(document.getElementById('auth-status')),
    username: (document.querySelector('#auth-status .auth-username') || {}).textContent,
  }));
  expect(authPos.inFooter, '#auth-status at the sidebar foot').toBe(true);
  expect(authPos.username).toBe('Admin');

  // ── AC-1/AC-3: header with the page title; the content region alone
  //    scrolls; shell tokens stay on the shell, unported pages keep theirs ──
  const shellLayout = await page.evaluate(() => {
    const region = document.getElementById('page-container');
    return {
      title: document.getElementById('page-title').textContent,
      titleColor: getComputedStyle(document.getElementById('page-title')).color,
      regionOverflowY: getComputedStyle(region).overflowY,
      regionBg: getComputedStyle(region).backgroundColor,
      pageBg: getComputedStyle(document.getElementById('page-dashboard')).backgroundColor,
      bodyBg: getComputedStyle(document.body).backgroundColor,
    };
  });
  expect(shellLayout.title).toBe('Dashboard');
  expect(shellLayout.titleColor, '#page-title uses --color-ink').toBe('rgb(23, 33, 43)');
  expect(shellLayout.regionOverflowY, 'the content region scrolls').toBe('auto');
  expect(shellLayout.regionBg, 'content region uses --color-ground').toBe('rgb(238, 241, 244)');
  // AC-3: unported page styles must not inherit the shell tokens.
  expect(shellLayout.pageBg, 'unported .page styles do not take --color-ground')
    .not.toBe('rgb(238, 241, 244)');
  expect(shellLayout.bodyBg, 'body keeps its own (unported) background')
    .not.toBe('rgb(238, 241, 244)');

  // ── AC-1: at 1440x900 the document does not scroll (Dashboard) ──
  await page.waitForFunction(
    () => document.getElementById('stat-total-contacts').textContent === '200',
    { timeout: 30000 });

  const docScrollDash = await page.evaluate(() => {
    const de = document.documentElement;
    return {
      vertical: de.scrollHeight > de.clientHeight,
      horizontal: de.scrollWidth > de.clientWidth,
    };
  });
  expect(docScrollDash.vertical, 'no document scroll at 1440x900 (Dashboard)').toBe(false);
  expect(docScrollDash.horizontal, 'no horizontal document scroll at 1440x900').toBe(false);

  // ── AC-1/AC-4/AC-6: clicking Contacts updates the hash and applies the
  //    route synchronously, before any async content write ──
  const countContactsGets = () => calls
    .filter((c) => c.method === 'GET' && /\/contacts(\?|&|$)/.test(c.url)).length;
  await stable(countContactsGets); // boot dashboard render fully settled
  const getsBeforeClick = countContactsGets();
  const probe = await page.evaluate(() => {
    document.querySelector('.nav-item[data-page="contacts"]').click();
    const activeNav = document.querySelector('.nav-item.active');
    const ariaNav = document.querySelector('.nav-item[aria-current="page"]');
    return {
      hash: location.hash,
      activePage: activeNav ? activeNav.dataset.page : null,
      ariaPage: ariaNav ? ariaNav.dataset.page : null,
      title: document.getElementById('page-title').textContent,
      activePanel: (document.querySelector('.page.active') || {}).id || null,
      hasContactCard: !!document.querySelector('#contacts-list .contact-card'),
    };
  });
  expect(probe.hash, 'a nav click updates the hash').toBe('#/contacts');
  // AC-6: route state flips synchronously, before the async content write.
  expect(probe.activePage).toBe('contacts');
  expect(probe.ariaPage, 'the active item carries aria-current="page"').toBe('contacts');
  expect(probe.title).toBe('Contacts');
  expect(probe.activePanel).toBe('page-contacts');
  expect(probe.hasContactCard, 'no async content may precede the route state')
    .toBe(false);

  // The contacts page renders; 200 rows => 3 paged GETs (limit=100, plus the
  // terminating empty page) for the list and 3 for the duplicate check.
  await page.waitForFunction(
    () => document.querySelectorAll('#contacts-list .contact-card').length === 200,
    { timeout: 30000 });
  await stable(countContactsGets);
  expect(countContactsGets() - getsBeforeClick,
    'a double render would double the /contacts API calls').toBe(6);

  // ── AC-4: a user hash edit that maps to the current page is ignored ──
  const samePageGets = countContactsGets();
  await page.evaluate(() => { location.hash = '#/contacts/'; });
  await page.waitForFunction(() => location.hash === '#/contacts/', { timeout: 5000 });
  await stable(countContactsGets);
  expect(countContactsGets(), 'same-page hash updates must not re-render')
    .toBe(samePageGets);
  // Restore the canonical hash (replaceState: no hashchange, no re-render)
  // so Back history stays #/contacts -> #/companies.
  await page.evaluate(() => { history.replaceState(null, '', '#/contacts'); });

  // ── AC-1: at 1440x900 the document does not scroll on Contacts (200
  //    rows) while the content region scrolls on its own ──
  const scrollState = await page.evaluate(() => {
    const de = document.documentElement;
    const region = document.getElementById('page-container');
    return {
      docScrolls: de.scrollHeight > de.clientHeight,
      regionScrolls: region.scrollHeight > region.clientHeight,
    };
  });
  expect(scrollState.docScrolls, 'no document scroll at 1440x900 (Contacts)').toBe(false);
  expect(scrollState.regionScrolls, 'the content region scrolls').toBe(true);

  // ── AC-1: a user hash edit routes; a reload on #/companies opens
  //    Companies; Back returns to the previous page; an unknown hash opens
  //    Dashboard ──
  await page.evaluate(() => { location.hash = '#/companies'; });
  await page.waitForFunction(
    () => location.hash === '#/companies'
      && document.getElementById('page-companies').classList.contains('active'),
    { timeout: 10000 });
  await expect(page.locator('#page-title')).toHaveText('Companies');

  await page.reload();
  await page.waitForFunction(
    () => location.hash === '#/companies'
      && document.getElementById('page-companies').classList.contains('active'),
    { timeout: 30000 });
  await page.waitForFunction(
    () => Auth.isAuthenticated && Auth.isAuthenticated(),
    { timeout: 20000 });
  await expect(page.locator('#page-title')).toHaveText('Companies');
  await expect(page.locator('.nav-item[data-page="companies"]'))
    .toHaveAttribute('aria-current', 'page');
  await expect(page.locator('#sidebar .sidebar-footer #auth-status .auth-username'))
    .toHaveText('Admin');

  await page.goBack();
  await page.waitForFunction(() => location.hash === '#/contacts', { timeout: 10000 });
  await page.waitForFunction(
    () => document.getElementById('page-contacts').classList.contains('active'),
    { timeout: 10000 });
  await expect(page.locator('#page-title')).toHaveText('Contacts');
  await expect(page.locator('.nav-item[data-page="contacts"]'))
    .toHaveAttribute('aria-current', 'page');

  await page.goto(INDEX + '#/nonsense-page');
  await page.waitForFunction(
    () => document.getElementById('page-dashboard').classList.contains('active'),
    { timeout: 30000 });
  await expect(page.locator('#page-title')).toHaveText('Dashboard');
  await expect(page.locator('.nav-item[data-page="dashboard"]'))
    .toHaveAttribute('aria-current', 'page');

  // ── AC-1: at 390x844 the sidebar is a top bar and the page does not
  //    scroll horizontally ──
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { location.hash = '#/contacts'; });
  await page.waitForFunction(
    () => document.querySelectorAll('#contacts-list .contact-card').length === 200,
    { timeout: 30000 });
  const narrow = await page.evaluate(() => {
    window.scrollTo(100, 0);
    const canScrollX = window.scrollX > 0;
    window.scrollTo(0, 0);
    const sb = document.getElementById('sidebar').getBoundingClientRect();
    const main = document.getElementById('main-content').getBoundingClientRect();
    return {
      canScrollX,
      sidebarTopBar: sb.top >= 0 && sb.width >= window.innerWidth - 1
        && main.top >= sb.bottom - 1,
    };
  });
  expect(narrow.canScrollX, 'no horizontal page scroll at 390x844').toBe(false);
  expect(narrow.sidebarTopBar, 'the sidebar becomes a top bar at <=900 px').toBe(true);

  expect(pageErrors, `page errors: ${pageErrors.join(' | ')}`).toEqual([]);
});

test('issue306 freeform (viewer)', async ({ page }) => {
  test.setTimeout(60000);
  const pageErrors = [];
  page.on('pageerror', (e) => pageErrors.push(String(e)));

  // Identity: the same production boot, but NON-ADMIN (role 'user').
  const calls = await boot(page, VIEWER_TOKEN, makeContacts(3));
  await page.setViewportSize({ width: 1440, height: 900 });

  const roles = await page.evaluate(() => (Auth.getCurrentUser() || {}).roles);
  expect(roles, 'the viewer pass runs as a NON-ADMIN (role "user")').toEqual(['user']);
  await expect.poll(
    () => calls.some((c) => /\/auth\/me/.test(c.url) && c.auth === 'Bearer ' + VIEWER_TOKEN),
    { timeout: 10000 }).toBe(true);

  // The page still renders: shell, nav, title and dashboard content.
  await expect(page.locator('#page-dashboard.active')).toBeVisible();
  await expect(page.locator('#page-title')).toHaveText('Dashboard');
  await expect(page.locator('.nav-item[data-page="dashboard"]'))
    .toHaveAttribute('aria-current', 'page');
  await expect(page.locator('#sidebar .sidebar-footer #auth-status .auth-username'))
    .toHaveText('Viewer One');

  // The admin-only control is absent for the viewer — on the Contacts page
  // itself, where an admin would see "+ Add Contact".
  await page.evaluate(() => { location.hash = '#/contacts'; });
  await page.waitForFunction(
    () => document.querySelectorAll('#contacts-list .contact-card').length === 3,
    { timeout: 20000 });
  await expect(page.locator('#page-title')).toHaveText('Contacts');
  await expect(page.locator('#btn-add-contact')).toBeHidden();
  const adminOnlyVisible = await page.evaluate(() =>
    Array.from(document.querySelectorAll('[data-admin-only="true"]'))
      .filter((el) => el.offsetParent !== null)
      .map((el) => el.id || el.className));
  expect(adminOnlyVisible, 'no admin-only control may be visible to a non-admin')
    .toEqual([]);

  // A full reload keeps the viewer role, reopens the hash route, and the
  // admin-only control stays absent.
  await page.reload();
  await page.waitForFunction(
    () => Auth.isAuthenticated && Auth.isAuthenticated(),
    { timeout: 20000 });
  expect(await page.evaluate(() => (Auth.getCurrentUser() || {}).roles)).toEqual(['user']);
  await page.waitForFunction(
    () => document.querySelectorAll('#contacts-list .contact-card').length === 3,
    { timeout: 20000 });
  await expect(page.locator('#page-contacts.active')).toBeVisible();
  await expect(page.locator('#page-title')).toHaveText('Contacts');
  await expect(page.locator('#sidebar .sidebar-footer #auth-status .auth-username'))
    .toHaveText('Viewer One');
  await expect(page.locator('#btn-add-contact')).toBeHidden();

  expect(pageErrors, `page errors: ${pageErrors.join(' | ')}`).toEqual([]);
});
